# Generated by Django 2.0.4 on 2018-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_country', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('make', models.CharField(max_length=200)),
                ('sold_by', models.CharField(max_length=200)),
                ('sale_price', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
